CREATE DATABASE db_gestion_de_tareas;

USE db_gestion_de_tareas;

CREATE TABLE IF NOT EXISTS USUARIOS(
    ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

INSERT INTO USUARIOS (NOMBRE_APELLIDO, EMAIL, PASSWORD) VALUES ('Javier', 'pXQp3@example.com', '123456');

CREATE TABLE IF NOT EXISTS TAREAS(
    ID_TAREA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    NOMBRE VARCHAR(255),
    COLOR VARCHAR(7),
    COMPLETADO BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
)

-- INSERTAR PARA PROBAR SI SE MUESTRA EN EL CONTENEDOR DEL LADO DEL CLIENTE...

-- CREATE TABLE IF NOT EXISTS PROGRESO_HISTORIAL(
--     ID_PROGRESO_HISTORIAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     ID_TAREA INT,
--     PROGRESO_ANTERIOR DECIMAL(5,2),
--     PROGRESO_NUEVO DECIMAL(5,2),
--     CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN ID_TAREA REFERENCES TAREAS(ID_TAREA)
-- )

-- INSERTAR PARA PROBAR SI SE MUESTRA EN EL CONTENEDOR DEL LADO DEL CLIENTE...